import os
import sys
import json
import time
import uuid
import re
import shutil
import tempfile
import threading
import subprocess
from pathlib import Path
from http.server import HTTPServer, BaseHTTPRequestHandler
from socketserver import ThreadingMixIn

# Handle pythonw.exe where stdout and stderr are None
if sys.stdout is None:
    sys.stdout = open(os.devnull, 'w')
if sys.stderr is None:
    sys.stderr = open(os.devnull, 'w')

PORT = 7823
VERSION = "2.0.0"

# Get user Downloads folder
def get_downloads_dir():
    try:
        import winreg
        sub_key = r'SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders'
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, sub_key) as key:
            downloads_dir = winreg.QueryValueEx(key, '{374DE290-123F-4565-9164-39C4925E467B}')[0]
            if os.path.isdir(downloads_dir):
                return downloads_dir
    except Exception:
        pass
    home_downloads = os.path.join(os.path.expanduser('~'), 'Downloads')
    if os.path.isdir(home_downloads):
        return home_downloads
    return os.path.expanduser('~')

DOWNLOADS_DIR = get_downloads_dir()

def check_ffmpeg():
    if shutil.which('ffmpeg'):
        return True
    # Check common paths (Windows + macOS Homebrew)
    common_paths = [
        '/opt/homebrew/bin/ffmpeg',
        '/usr/local/bin/ffmpeg',
        r'C:\ffmpeg\bin\ffmpeg.exe',
        r'C:\Program Files\ffmpeg\bin\ffmpeg.exe',
        os.path.join(os.path.expanduser('~'), r'AppData\Local\Microsoft\WinGet\Links\ffmpeg.exe')
    ]
    for p in common_paths:
        if os.path.isfile(p):
            return True
    return False

def check_ytdlp():
    try:
        import yt_dlp
        return True
    except ImportError:
        return shutil.which('yt-dlp') is not None

# Global jobs store
# id -> job dict
jobs = {}
jobs_lock = threading.Lock()

def sanitize_filename(name):
    if not name:
        return ""
    # remove invalid filename characters
    s = re.sub(r'[<>:"/\\|?*\x00-\x1f]', '_', str(name))
    return s.strip('. ')[:180]

def create_netscape_cookie_file(cookies, filepath):
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by Descargador Companion\n\n")
        for c in cookies:
            try:
                domain = c.get('domain', '')
                if not domain:
                    continue
                include_sub = "TRUE" if domain.startswith('.') else "FALSE"
                path = c.get('path', '/') or '/'
                secure = "TRUE" if c.get('secure', False) else "FALSE"
                exp = c.get('expirationDate')
                if exp is None:
                    # session cookie: set 1 year into the future
                    exp = int(time.time()) + 86400 * 365
                else:
                    exp = int(exp)
                name = c.get('name', '')
                value = c.get('value', '')
                if not name:
                    continue
                f.write(f"{domain}\t{include_sub}\t{path}\t{secure}\t{exp}\t{name}\t{value}\n")
            except Exception:
                pass

class CustomLogger:
    def __init__(self, job):
        self.job = job

    def debug(self, msg):
        self._add(msg)

    def info(self, msg):
        self._add(msg)

    def warning(self, msg):
        self._add(f"WARN: {msg}")

    def error(self, msg):
        self._add(f"ERROR: {msg}")

    def _add(self, msg):
        if not msg:
            return
        m = str(msg).strip()
        if not m:
            return
        with jobs_lock:
            log = self.job.get('log', [])
            log.append(m)
            if len(log) > 100:
                self.job['log'] = log[-100:]
            else:
                self.job['log'] = log

def run_download_thread(job_id, params):
    job = jobs[job_id]
    temp_cookie_path = None

    try:
        import yt_dlp
    except ImportError:
        with jobs_lock:
            job['status'] = 'error'
            job['error'] = 'yt-dlp no está instalado. Ejecuta instalar.bat en la carpeta companion.'
        return

    try:
        page_url = params.get('pageUrl', '')
        stream_url = params.get('streamUrl', '')
        headers = params.get('headers') or {}
        cookies = params.get('cookies') or []
        filename = params.get('filename') or ''
        mode = params.get('mode', 'stream')

        target_url = stream_url if (stream_url and (mode == 'stream' or not page_url)) else (page_url or stream_url)

        if not target_url:
            with jobs_lock:
                job['status'] = 'error'
                job['error'] = 'No se proporcionó URL de video ni de página'
            return

        # Prepare cookies
        if cookies:
            fd, temp_cookie_path = tempfile.mkstemp(prefix='comp_cookies_', suffix='.txt')
            os.close(fd)
            create_netscape_cookie_file(cookies, temp_cookie_path)

        # Output template
        clean_name = sanitize_filename(filename)
        if clean_name:
            outtmpl = os.path.join(DOWNLOADS_DIR, f"{clean_name}.%(ext)s")
        else:
            outtmpl = os.path.join(DOWNLOADS_DIR, "%(title)s.%(ext)s")

        def progress_hook(d):
            if job.get('cancel_requested'):
                raise Exception('DESCARGA_CANCELADA_POR_USUARIO')

            status = d.get('status')
            with jobs_lock:
                if status == 'downloading':
                    job['status'] = 'running'
                    total = d.get('total_bytes') or d.get('total_bytes_estimate') or 0
                    downloaded = d.get('downloaded_bytes', 0)
                    if total > 0:
                        job['percent'] = min(99.0, round((downloaded / total) * 100, 1))
                    elif '_percent_str' in d:
                        try:
                            clean_p = d['_percent_str'].strip().replace('%', '')
                            job['percent'] = min(99.0, float(clean_p))
                        except Exception:
                            pass
                    
                    if '_speed_str' in d:
                        job['speed'] = d['_speed_str'].strip()
                    if '_eta_str' in d:
                        job['eta'] = d['_eta_str'].strip()

                elif status == 'finished':
                    job['status'] = 'running'
                    job['percent'] = 99.0
                    fn = d.get('filename')
                    if fn:
                        job['filepath'] = os.path.abspath(fn)

        ydl_opts = {
            'outtmpl': outtmpl,
            'progress_hooks': [progress_hook],
            'logger': CustomLogger(job),
            'nocheckcertificate': True,
            'ignoreerrors': False,
            'retries': 10,
            'fragment_retries': 10,
            'concurrent_fragment_downloads': 5,
            'windowsfilenames': True,
            'no_warnings': False,
        }

        if headers:
            ydl_opts['http_headers'] = headers

        if temp_cookie_path:
            ydl_opts['cookiefile'] = temp_cookie_path

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            with jobs_lock:
                job['status'] = 'running'
            info = ydl.extract_info(target_url, download=True)
            if info:
                # Find final filename
                try:
                    final_fn = ydl.prepare_filename(info)
                    if final_fn:
                        job['filepath'] = os.path.abspath(final_fn)
                except Exception:
                    pass

        with jobs_lock:
            if not job.get('cancel_requested'):
                job['status'] = 'done'
                job['percent'] = 100.0
                job['speed'] = ''
                job['eta'] = ''

    except Exception as e:
        msg = str(e)
        with jobs_lock:
            if 'DESCARGA_CANCELADA_POR_USUARIO' in msg or job.get('cancel_requested'):
                job['status'] = 'cancelled'
            else:
                job['status'] = 'error'
                job['error'] = msg
    finally:
        if temp_cookie_path and os.path.exists(temp_cookie_path):
            try:
                os.remove(temp_cookie_path)
            except Exception:
                pass


class ThreadedHTTPServer(ThreadingMixIn, HTTPServer):
    daemon_threads = True

class CompanionHandler(BaseHTTPRequestHandler):
    def send_cors_headers(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, DELETE, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type, Authorization, *')

    def send_json(self, data, status=200):
        try:
            body = json.dumps(data, ensure_ascii=False).encode('utf-8')
            self.send_response(status)
            self.send_cors_headers()
            self.send_header('Content-Type', 'application/json; charset=utf-8')
            self.send_header('Content-Length', str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        except (BrokenPipeError, ConnectionResetError, ConnectionAbortedError, OSError):
            pass

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_cors_headers()
        self.end_headers()

    def do_GET(self):
        path = self.path.split('?')[0]

        if path == '/health':
            ytdlp_ok = check_ytdlp()
            ffmpeg_ok = check_ffmpeg()
            self.send_json({
                'version': VERSION,
                'ytdlp': ytdlp_ok,
                'ffmpeg': ffmpeg_ok,
                'downloadsDir': DOWNLOADS_DIR
            })
            return

        if path == '/jobs':
            with jobs_lock:
                # return clean jobs without non-serializable objects
                clean_jobs = []
                for j in jobs.values():
                    clean_jobs.append({
                        'id': j.get('id'),
                        'status': j.get('status'),
                        'percent': j.get('percent', 0),
                        'eta': j.get('eta', ''),
                        'speed': j.get('speed', ''),
                        'filepath': j.get('filepath'),
                        'error': j.get('error'),
                        'log': j.get('log', [])[-20:]
                    })
            self.send_json({'jobs': clean_jobs})
            return

        if path.startswith('/status/'):
            job_id = path[len('/status/'):]
            with jobs_lock:
                j = jobs.get(job_id)
                if not j:
                    self.send_json({'error': 'Job not found', 'status': 'error'}, status=404)
                    return
                res = {
                    'id': j.get('id'),
                    'status': j.get('status'),
                    'percent': j.get('percent', 0),
                    'eta': j.get('eta', ''),
                    'speed': j.get('speed', ''),
                    'filepath': j.get('filepath'),
                    'error': j.get('error'),
                    'log': j.get('log', [])[-20:]
                }
            self.send_json(res)
            return

        self.send_json({'error': 'Not found'}, status=404)

    def do_POST(self):
        path = self.path.split('?')[0]

        if path == '/open-folder':
            try:
                if sys.platform == 'darwin':
                    subprocess.Popen(['open', DOWNLOADS_DIR])
                elif sys.platform == 'win32':
                    os.startfile(DOWNLOADS_DIR)
                else:
                    subprocess.Popen(['xdg-open', DOWNLOADS_DIR])
                self.send_json({'ok': True})
            except Exception as e:
                try:
                    cmd = ['open' if sys.platform == 'darwin' else 'explorer', DOWNLOADS_DIR]
                    subprocess.Popen(cmd)
                    self.send_json({'ok': True})
                except Exception as e2:
                    self.send_json({'ok': False, 'error': str(e2)}, status=500)
            return

        if path == '/shutdown':
            self.send_json({'ok': True})
            def do_shutdown():
                time.sleep(0.5)
                os._exit(0)
            threading.Thread(target=do_shutdown, daemon=True).start()
            return

        if path == '/download':
            content_len = int(self.headers.get('Content-Length', 0))
            body_bytes = self.rfile.read(content_len) if content_len > 0 else b'{}'
            try:
                params = json.loads(body_bytes.decode('utf-8'))
            except Exception:
                params = {}

            job_id = f"job_{int(time.time() * 1000)}_{uuid.uuid4().hex[:6]}"
            job = {
                'id': job_id,
                'status': 'starting',
                'percent': 0.0,
                'eta': '',
                'speed': '',
                'filepath': None,
                'error': None,
                'log': [],
                'cancel_requested': False
            }

            with jobs_lock:
                jobs[job_id] = job

            t = threading.Thread(target=run_download_thread, args=(job_id, params), daemon=True)
            t.start()

            self.send_json({'id': job_id, 'ok': True})
            return

        self.send_json({'error': 'Not found'}, status=404)

    def do_DELETE(self):
        path = self.path.split('?')[0]

        if path.startswith('/cancel/'):
            job_id = path[len('/cancel/'):]
            with jobs_lock:
                j = jobs.get(job_id)
                if j:
                    j['cancel_requested'] = True
                    j['status'] = 'cancelled'
            self.send_json({'ok': True})
            return

        self.send_json({'error': 'Not found'}, status=404)

    def log_message(self, format, *args):
        # suppress default console noise
        pass

def main():
    try:
        server = ThreadedHTTPServer(('127.0.0.1', PORT), CompanionHandler)
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            pass
        finally:
            server.server_close()
    except Exception as e:
        log_file = os.path.join(os.path.dirname(__file__), 'companion.log')
        with open(log_file, 'a', encoding='utf-8') as f:
            f.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] ERROR: {e}\n")
            import traceback
            traceback.print_exc(file=f)

if __name__ == '__main__':
    main()

